version: "3.9"

networks:
  mysite-net:
    driver: bridge

volumes:
  postgres:
  mysite:

services:
  mysite:
    image: service/mysite:1.0.0
    container_name: mysite
    profiles: ["local", "all"]
    build: .
    command: ["./docker/local/docker-entrypoint.sh"]
    volumes:
      - .:/mysite
    ports:
      - "8000:8000"
    networks:
      - mysite-net
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
    depends_on:
      - postgres

  postgres:
    image: postgres:13.4
    container_name: postgres
    profiles: ["local", "all"]
    ports:
      - 5432:5432
    networks:
      - mysite-net
    environment:
      - POSTGRES_USER=mysite
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mysite
    volumes:
      - postgres:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    profiles: ["local", "all"]
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - mysite-net