# Generated by Django 2.2.3 on 2019-07-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Published'), (0, 'Draft'), (2, 'Archived')], default=0),
        ),
    ]
